Repository binaryai/sdk, pull requests merged in 2020-06, with the labels that each got.

#12 feat: add BinaryAIException
  binaryai/__init__.py
  binaryai/client.py
  binaryai/error.py
  binaryai/function.py
  binaryai/ida.py
  examples/ida_binaryai.py
Labels: enhancement

#51 class BinaryAIException super bug fix
  binaryai/error.py
Labels: bug

#55 docs: add token registration
  README.md
  docs/installation.md
  docs/registration.md
  docs/usage.md
Labels: documentation
